"""recrutamento — Migration inicial."""
import uuid
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('rh', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='rh.departamento')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='rh.cargo')),
                ('status', models.CharField(choices=[('rascunho','Rascunho'),('aberta','Aberta'),('pausada','Pausada'),('fechada','Fechada'),('cancelada','Cancelada')], default='rascunho', max_length=15)),
                ('modalidade', models.CharField(default='presencial', max_length=15)),
                ('tipo_contrato', models.CharField(default='clt', max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('requisitos', models.TextField(blank=True)),
                ('beneficios', models.TextField(blank=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_oculto', models.BooleanField(default=False)),
                ('vagas_count', models.IntegerField(default=1)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('prazo_inscricao', models.DateField(blank=True, null=True)),
                ('descricao_ia', models.BooleanField(default=False)),
                ('perguntas_entrevista', models.JSONField(blank=True, default=list)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_responsavel', to='accounts.usuario')),
                ('publicada_em', models.DateTimeField(blank=True, null=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
            ],
            options={'db_table': 'recrutamento_vaga', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField()),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('fonte', models.CharField(default='site', max_length=15)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='recrutamento/curriculos/')),
                ('resumo_ia', models.TextField(blank=True)),
                ('score_fit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('indicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to='rh.colaborador')),
                ('bloqueado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
            ],
            options={'db_table': 'recrutamento_candidato', 'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='recrutamento.vaga')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='recrutamento.candidato')),
                ('etapa', models.CharField(default='triagem', max_length=15)),
                ('score', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas_avaliadas', to='accounts.usuario')),
                ('data_movimentacao', models.DateTimeField(auto_now=True)),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('salario_pretendido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
            ],
            options={'db_table': 'recrutamento_candidatura', 'ordering': ['-data_movimentacao']},
        ),
        migrations.AlterUniqueTogether(name='candidatura', unique_together={('vaga', 'candidato')}),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='recrutamento.candidatura')),
                ('entrevistador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='accounts.usuario')),
                ('formato', models.CharField(default='video', max_length=15)),
                ('status', models.CharField(default='agendada', max_length=15)),
                ('data_hora', models.DateTimeField()),
                ('duracao_min', models.IntegerField(default=60)),
                ('link_video', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('nota_tecnica', models.IntegerField(blank=True, null=True)),
                ('nota_comportamental', models.IntegerField(blank=True, null=True)),
                ('recomendacao', models.CharField(blank=True, max_length=10)),
                ('perguntas_usadas', models.JSONField(blank=True, default=list)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.usuario')),
            ],
            options={'db_table': 'recrutamento_entrevista', 'ordering': ['data_hora']},
        ),
    ]
